name: ao-localnet

configs:
  ao-wallet:
    file: ./ao-wallet.json
  ardrive-web-app-config:
    file: ./ardrive-web/app-config.json
  mu-env:
    file: ./mu/.env

volumes:
  arlocal-db:

services:

  arlocal:
    build: ./arlocal
    ports:
      - 4000:80
    volumes:
      - arlocal-db:/mnt

  ardrive-web:
    depends_on:
      - arlocal
    build: ./ardrive-web
    configs:
      - source: ardrive-web-app-config
        target: /usr/local/apache2/htdocs/assets/assets/config/dev.json
    ports:
      - 4001:80

  mu:
    build: ./mu
    configs:
      - source: ao-wallet
        target: /usr/app/ao-wallet.json
      - source: mu-env
        target: /usr/app/.env
    ports:
      - 4002:80

  su:
    depends_on:
      su-database:
        condition: service_healthy
    build: ./su
    configs:
      - source: ao-wallet
        target: /usr/app/ao-wallet.json
    env_file: ./su/.env
    ports:
      - 4003:80

  su-database:
    image: postgres
    environment:
      - POSTGRES_USER=su_user
      - POSTGRES_PASSWORD=su_pass
      - POSTGRES_DB=su_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U su_user"]
      interval: 1s
