name: aonix-localnet

volumes:
  arlocal-db:

services:
  arlocal:
    build: ./arlocal
    ports:
      - 4000:80
    volumes:
      - arlocal-db:/mnt
  ardrive-web:
    depends_on:
      - arlocal
    build: ./ardrive-web
    ports:
      - 4001:80
