name: aonix-localnet

configs:
  ardrive-web-app-config:
    file: ardrive-web/app-config.json

volumes:
  arlocal-db:

services:
  arlocal:
    build: ./arlocal
    ports:
      - 4000:80
    volumes:
      - arlocal-db:/mnt
  ardrive-web:
    depends_on:
      - arlocal
    build: ./ardrive-web
    configs:
      - source: ardrive-web-app-config
        target: /usr/local/apache2/htdocs/assets/assets/config/dev.json
    ports:
      - 4001:80
